# NOTE: Development config (also make any relevant changes to
# Dockerfile-app)


FROM frolvlad/alpine-python-machinelearning
MAINTAINER Open State Foundation <developers@openstate.eu>

ENV FLASK_APP=app
ENV FLASK_DEBUG=0

WORKDIR /opt/otc
COPY docker/requirements.txt .

RUN apk add --update build-base tzdata libffi-dev python3-dev postgresql-dev \
  && pip install --upgrade pip \
  && pip install --no-cache-dir -r requirements.txt \
  && cp /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime \
  && echo "Europe/Amsterdam" > /etc/timezone \
  && apk del build-base tzdata

COPY app app
COPY models models
COPY config.py config.py

CMD flask run --host=0.0.0.0
