version: "3.1"
services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-dev/:/etc/nginx/
    restart: "no"
  app:
    build:
      dockerfile: docker/Dockerfile-app-dev
    ports:
    - 5000:5000
    restart: "no"
  mysql:
    restart: "no"
networks:
  otc:
  nginx-load-balancer:
